version: '3.8'

services:
  hello-world:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-hello-world
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=hello_world_app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hello-world-network

networks:
  hello-world-network:
    driver: bridge